"""The publication lifecycle, as nine distinct and non-collapsing states.

    generated                — bytes exist, produced by a named generator, reproducibly.
    validated                — those bytes satisfy the artifact's own schema and checks.
    packaged                 — a copy exists in the disposable staging area, hash-verified.
    present                  — a descriptor for it exists and is structurally sound.
    uploaded                 — the bytes exist at the immutable key on the approved origin.
    published                — release status is `published`, with a publication date.
    approved                 — every required approval is granted against a decision record.
    active                   — activation is explicitly active AND explicitly authorized.
    eligible_for_environment — everything a given environment requires holds at once.

The first three are Knowledge Base stages: they describe preparing bytes. `present` onward are
the Backend contract's own states and are computed by `eligibility.py`, which is a port of the
Backend's implementation rather than a second opinion.

The point of the module is the *edges that do not exist*. Nothing here derives a later state
from an earlier one. `state_of` takes each state as an independently supplied observation and
its only job is to notice when a caller has claimed an implication that is not permitted:

    generated       does not mean validated
    validated       does not mean packaged
    packaged        does not mean uploaded
    present         does not mean uploaded, and storage presence does not mean published
    uploaded        does not mean published
    published       does not mean approved
    approved        does not mean active
    active          does not mean eligible
    a git commit or a merged pull request means none of them

Each unearned implication is reported as `KB_STATE_COLLAPSE`, naming both states. Absent, null,
unknown or conflicting input is not a state — it is a refusal.
"""

from .reasons import reason

#: Ordered for reporting only. Order is *not* implication: a later state is never inferred
#: from an earlier one, and the order carries no license to do so.
LIFECYCLE_STATES = (
    "generated",
    "validated",
    "packaged",
    "present",
    "uploaded",
    "published",
    "approved",
    "active",
    "eligible_for_environment",
)

#: Stages this repository can observe for itself.
KB_OWNED_STATES = ("generated", "validated", "packaged")

#: Stages only infrastructure or governance can establish. The Knowledge Base can never
#: observe these as true from inside a repository, so its tooling records them false and says
#: why, rather than leaving them unset and letting a reader assume.
EXTERNALLY_ESTABLISHED_STATES = (
    "uploaded",
    "published",
    "approved",
    "active",
    "eligible_for_environment",
)

#: `(earlier, later, why)` — every implication a reader might be tempted to draw, and the
#: sentence explaining why it does not hold. This table is the contract of this module.
FORBIDDEN_IMPLICATIONS = (
    ("generated", "validated", "generated bytes are unvalidated bytes until a validator says otherwise"),
    ("validated", "packaged", "a validated artifact has not been packaged until it is staged and re-hashed"),
    ("packaged", "uploaded", "packaging writes to a disposable local directory, not to storage"),
    ("present", "uploaded", "a descriptor describing an object does not put that object anywhere"),
    ("uploaded", "published", "storage presence is not publication; bytes at a key are just bytes at a key"),
    ("uploaded", "approved", "storage presence is not approval; nobody reviewed a byte range"),
    ("published", "approved", "publication is a release act, approval is a governance act"),
    ("approved", "active", "approval permits activation; it does not perform it"),
    ("active", "eligible_for_environment", "activation is global, eligibility is per environment"),
    ("present", "eligible_for_environment", "candidate existence is never eligibility"),
)

#: Facts that establish no state at all, recorded so a plan can say so explicitly.
NON_AUTHORITIES = (
    "a git commit",
    "a merged pull request",
    "a green CI run",
    "a passing test suite",
    "a completed decision set",
    "the existence of a candidate file",
    "a proposed object key",
    "a dry-run plan",
)


class StateCollapse(Exception):
    """Raised when a caller asserts an implication the lifecycle does not permit."""


def state_of(observations, path="lifecycle"):
    """Assemble a lifecycle state map from independently observed values.

    `observations` must supply every state in `LIFECYCLE_STATES` as an explicit `True` or
    `False`. Anything else — absent, `None`, a string, a truthy object — is a refusal, because
    a state that has not been observed is not a state that is false; it is a state nobody
    checked, and treating "unknown" as either value is how governance data gets invented.

    Returns `(states, reasons)`. `states` is `None` when the observations cannot be trusted.
    """
    reasons = []

    if not isinstance(observations, dict):
        return None, [reason("KB_STATE_COLLAPSE", path, "lifecycle observations must be a mapping")]

    for state in LIFECYCLE_STATES:
        if state not in observations:
            reasons.append(
                reason(
                    "KB_STATE_COLLAPSE",
                    "%s.%s" % (path, state),
                    "state was never observed; an unobserved state is not a false state and "
                    "must not be defaulted",
                )
            )
        elif not isinstance(observations[state], bool):
            reasons.append(
                reason(
                    "KB_STATE_COLLAPSE",
                    "%s.%s" % (path, state),
                    "state is %r, which is neither true nor false; unknown governance fails "
                    "closed rather than resolving" % (observations[state],),
                )
            )

    unknown = set(observations) - set(LIFECYCLE_STATES)
    if unknown:
        reasons.append(
            reason(
                "KB_STATE_COLLAPSE",
                path,
                "unknown lifecycle state(s) %s; the state set is closed" % ", ".join(sorted(unknown)),
            )
        )

    if reasons:
        return None, reasons

    states = {state: observations[state] for state in LIFECYCLE_STATES}
    return states, check_no_collapse(states, path)


def check_no_collapse(states, path="lifecycle"):
    """Report every unearned state assertion in a state map.

    The enforced rule is the strong one, and it does not depend on which other states happen
    to be true: **no externally-established state may be asserted true by this tooling at
    all.** `uploaded`, `published`, `approved`, `active` and `eligible_for_environment` are
    established by infrastructure or by governance, and a repository cannot observe any of
    them. A plan claiming one is not reporting an observation; it is inventing one, and the
    weaker pairwise rule would let it through whenever the state it was collapsing from
    happened to be false.

    On top of that, when a forbidden pair *is* both-true, the report names the specific
    implication the caller looks to be drawing, so the failure says "packaged does not mean
    uploaded" rather than only "uploaded is not observable".

    `generated`, `validated` and `packaged` may legitimately all be true together: this
    repository observes each of them directly and independently. That they are independent is
    not asserted here — it is proved by the mutation tests, which flip one input and require
    exactly one output to move.
    """
    reasons = []

    for state in EXTERNALLY_ESTABLISHED_STATES:
        if states.get(state) is not True:
            continue

        grounds = [
            (earlier, why)
            for earlier, later, why in FORBIDDEN_IMPLICATIONS
            if later == state and states.get(earlier) is True
        ]
        if grounds:
            detail = "; ".join(
                "%s is true, but %s does not mean %s: %s" % (earlier, earlier, state, why)
                for earlier, why in grounds
            )
        else:
            detail = "no earlier state was even asserted as grounds"

        reasons.append(
            reason(
                "KB_STATE_COLLAPSE",
                "%s.%s" % (path, state),
                "%s is asserted true, but it can only be established outside this repository "
                "and this tooling never establishes it (%s)" % (state, detail),
            )
        )

    return reasons


def kb_observable_states():
    """The states this tooling is entitled to set true, with the reason for the rest.

    Every state the Knowledge Base cannot observe is returned false *with an explanation*, so
    a generated plan never carries a bare `false` a reader might mistake for "not yet checked".
    """
    return {
        "uploaded": "no upload has occurred and this tooling has no code path that could perform one",
        "published": "publication is a governance act recorded outside this repository",
        "approved": "approval requires an authoritative decision record; see governance.py",
        "active": "activation requires an explicit activation authorization, which does not exist",
        "eligible_for_environment": "eligibility is the Backend's computation over a published, "
        "approved, unblocked, activated descriptor; none of those hold",
    }
