"""Deterministic normalization for the WellaPath symptom vocabulary (W2).

This module is the *reference implementation* of the normalization contract
documented in `docs/VOCABULARY_NORMALIZATION_SPEC.md`. Mobile and Backend must
reproduce it exactly; `search_index.normalized_forms` in the vocabulary artifact
is generated by this code so that consumers can simply look values up instead of
re-implementing it.

Safety properties this function is required to hold (all covered by tests):

  * Pure  — output depends only on the input string. No locale, no clock,
            no randomness, no dictionary lookups, no network.
  * Total — every `str` input produces a `str` output; never raises on content.
  * Lossless for clinical distinctions — negation words, laterality words,
    severity words, duration words, ages, pregnancy words and digits all
    survive normalization verbatim.
  * No inference — no stemming, no plural folding, no stopword removal, no
    spelling correction, no edit-distance, no substring matching, no synonym
    expansion. Those are authored data (`search.aliases`), never algorithms.
"""

import unicodedata

NORMALIZATION_VERSION = "1.0.0"

# --- character variant folding -------------------------------------------------
# Applied *before* case folding so that the mapping is independent of case.

# Written as explicit codepoints rather than literal glyphs so the mapping stays
# reviewable in a diff and cannot be corrupted by an editor re-encoding the file.

# Apostrophe-like characters collapse to ASCII "'" and are then deleted, so
# "Ludwig's angina" and "Ludwig\u2019s angina" both give "ludwigs angina".
_APOSTROPHE_CODEPOINTS = (
    0x2018,  # LEFT SINGLE QUOTATION MARK
    0x2019,  # RIGHT SINGLE QUOTATION MARK
    0x201B,  # SINGLE HIGH-REVERSED-9 QUOTATION MARK
    0x02B9,  # MODIFIER LETTER PRIME
    0x02BB,  # MODIFIER LETTER TURNED COMMA
    0x02BC,  # MODIFIER LETTER APOSTROPHE
    0x00B4,  # ACUTE ACCENT
    0x0060,  # GRAVE ACCENT
)

# Dash-like characters collapse to ASCII "-", which the punctuation pass then
# turns into a single space: "chest-pain" and "chest\u2014pain" -> "chest pain".
_DASH_CODEPOINTS = (
    0x2010,  # HYPHEN
    0x2011,  # NON-BREAKING HYPHEN
    0x2012,  # FIGURE DASH
    0x2013,  # EN DASH
    0x2014,  # EM DASH
    0x2015,  # HORIZONTAL BAR
    0x2212,  # MINUS SIGN
    0xFE58,  # SMALL EM DASH
    0xFE63,  # SMALL HYPHEN-MINUS
)

# Space-like characters. NFKC already folds most of these; they are listed so the
# behaviour is guaranteed by this module rather than inherited from NFKC.
_SPACE_CODEPOINTS = (
    0x00A0,  # NO-BREAK SPACE
    0x1680,  # OGHAM SPACE MARK
    0x2000,  # EN QUAD
    0x2001,  # EM QUAD
    0x2002,  # EN SPACE
    0x2003,  # EM SPACE
    0x2004,  # THREE-PER-EM SPACE
    0x2005,  # FOUR-PER-EM SPACE
    0x2006,  # SIX-PER-EM SPACE
    0x2007,  # FIGURE SPACE
    0x2008,  # PUNCTUATION SPACE
    0x2009,  # THIN SPACE
    0x200A,  # HAIR SPACE
    0x200B,  # ZERO WIDTH SPACE
    0x202F,  # NARROW NO-BREAK SPACE
    0x205F,  # MEDIUM MATHEMATICAL SPACE
    0x3000,  # IDEOGRAPHIC SPACE
    0xFEFF,  # ZERO WIDTH NO-BREAK SPACE (BOM)
)

_VARIANT_MAP = {}
for _cp in _APOSTROPHE_CODEPOINTS:
    _VARIANT_MAP[_cp] = "'"
for _cp in _DASH_CODEPOINTS:
    _VARIANT_MAP[_cp] = "-"
for _cp in _SPACE_CODEPOINTS:
    _VARIANT_MAP[_cp] = " "

_ASCII_DIGITS = frozenset("0123456789")


def _is_digit_at(chars, i):
    return 0 <= i < len(chars) and chars[i] in _ASCII_DIGITS


def normalize(value):
    """Return the normalized search form of `value`.

    Pipeline (each step is individually covered by tests in
    `testing/vocabulary/test_vocabulary_v2.py`):

      1. Variant folding, then Unicode NFKC normalization, then variant folding
         again: apostrophe-like -> "'", dash-like -> "-", exotic spaces -> " ".
         The fold runs on both sides of NFKC because NFKC decomposes some of
         these characters into forms the map would otherwise miss.
      3. Case folding via `str.casefold()` (Unicode-aware; handles "ß" -> "ss").
      4. Delete ASCII apostrophes with no replacement.
      5. Punctuation pass, character by character:
           - letters and digits (any script) are kept;
           - "." is kept when it sits directly between two ASCII digits
             (decimal point: "38.5");
           - "/" is kept when it sits directly between two ASCII digits
             (ratio / blood pressure: "140/90");
           - "," is deleted when it sits directly between two ASCII digits
             (thousands separator: "1,000" -> "1000");
           - every other character becomes a single space.
      6. Collapse runs of whitespace to one ASCII space; strip the ends.

    Diacritics are deliberately *not* stripped — see
    `docs/VOCABULARY_NORMALIZATION_SPEC.md` §"Deferred: diacritic folding".
    Folding them could merge two authored aliases that are clinically distinct;
    the validator would catch such a collision, but the decision is a
    locale-gated, clinically reviewed one and is out of scope for W2 Step 1.
    """
    if not isinstance(value, str):
        raise TypeError("normalize() expects str, got %r" % type(value).__name__)

    # Variant folding runs on both sides of NFKC. Some of these characters are
    # themselves decomposed by NFKC into something the map would no longer
    # recognise — U+00B4 ACUTE ACCENT becomes SPACE + U+0301 COMBINING ACUTE,
    # for example — so mapping only afterwards would silently miss them. Running
    # it first catches those; running it again catches anything NFKC produces.
    # The map is idempotent on its own output, so the second pass is safe.
    s = value.translate(_VARIANT_MAP)
    s = unicodedata.normalize("NFKC", s)
    s = s.translate(_VARIANT_MAP)
    s = s.casefold()
    s = s.replace("'", "")

    chars = list(s)
    out = []
    for i, ch in enumerate(chars):
        if ch.isalnum():
            out.append(ch)
        elif ch == "." and _is_digit_at(chars, i - 1) and _is_digit_at(chars, i + 1):
            out.append(ch)
        elif ch == "/" and _is_digit_at(chars, i - 1) and _is_digit_at(chars, i + 1):
            out.append(ch)
        elif ch == "," and _is_digit_at(chars, i - 1) and _is_digit_at(chars, i + 1):
            continue  # thousands separator: delete, do not split the number
        else:
            out.append(" ")

    return " ".join("".join(out).split())


def normalize_token_id(token_id):
    """Normalized search form of a stable token ID.

    Token IDs are `lowercase_snake_case`; the underscore is the word separator,
    so it becomes a space before the standard pipeline runs. `chest_pain` yields
    `chest pain`.
    """
    if not isinstance(token_id, str):
        raise TypeError("normalize_token_id() expects str")
    return normalize(token_id.replace("_", " "))


def derive_label_from_token_id(token_id):
    """Mechanically derive a display label from a token ID.

    This is a *derivation*, not authored clinical copy. Entries produced this
    way are stamped `display.label_source = "derived_from_token_id"` and
    `display.display_safe = false`, and consumers must not surface them to
    patients until a clinical reviewer approves a real label. Kept here so the
    derivation is defined in exactly one place and is reproducible.
    """
    if not isinstance(token_id, str):
        raise TypeError("derive_label_from_token_id() expects str")
    words = token_id.split("_")
    if not words or not words[0]:
        return token_id
    return " ".join([words[0].capitalize()] + words[1:])
